# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/mubu_create_doc.har

import pytest
from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from httprunner import Parameters

from testcases.mubu_login_test import TestCaseMubuLogin as MubuLogin


class TestCaseMubuCreateDoc(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "title-node1Text-node2Text": [
                    ["demo1", "1abc", "1def"],
                    ["demo2", "2abc", "2def"],
                ],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("create new doc")
        .variables(**{"host": "mubu.com", "memberId": "${gen_memberId()}"})
        .variables(phone="18613143458", password="moFrwx$!kz3RTRm@Q*aV")
        .variables(title="demo123", node1Text="abc", node2Text="def")
        .verify(False)
        .base_url("https://${host}/")
    )

    teststeps = [
        Step(
            RunTestCase("login mubu")
            .with_variables(phone="18613143458", password="moFrwx$!kz3RTRm@Q*aV")
            .call(MubuLogin)
            .export(*["unreadCount"])
        ),
        Step(
            RunRequest("/api/list/create_doc")
            .post("/api/list/create_doc")
            .with_headers(
                **{
                    "content-length": "17",
                    "unreadCount": "'$unreadCount'",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1523574909.1567243126",
                    "mubu_inner": "1",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1594282707",
                    "data_unique_id": "c1e5cc1b-2b44-4347-bddb-7a0dd0f7b479",
                    "_gid": "GA1.2.1085584436.1595559677",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "s_v_web_id": "verify_kczo59ky_FlxKIV7C_zhEr_4z2C_8BnV_9GRIK1h2TVip",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "0eef99c5-4fe4-4cfe-abe2-5b34a3bcbb02",
                    "data-unique-id": "2e27d230-ce3d-11ea-ad68-83a977aed8cc",
                    "SESSION": "b0f4bb9a-3ad2-40be-ad79-e473540252f2",
                    "_gat": "1",
                    "reg_prepareId": "1738498487c-1738498473b-4e13-a558-df609f247eae",
                    "reg_focusId": "1812fb5d-034f-4e13-a558-17384984e5a",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTU5ODI0OTQ0NCwiaWF0IjoxNTk1NjU3NDQ0fQ.ZoOUyXDJZCeDyTifv2Lb3R0tGkkLOE6-Hj2XFUCLtAl_qk2hc9-ly-Gyvh2PVw0lfxR2Jxj9DMaeRgOnO9akSw",
                    "user_persistence": "0a3a3a87-2844-47be-90a5-9cc3e1120cec",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595657444",
                    "SLARDAR_WEB_ID": "ab29576c-6721-4297-b655-037dcf40f27c",
                }
            )
            .with_data({"folderId": "0", "type": "0"})
            .extract()
            .with_jmespath("body.data.id", "docId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/doc$docId")
            .get("/doc$docId")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1523574909.1567243126",
                    "mubu_inner": "1",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1594282707",
                    "data_unique_id": "c1e5cc1b-2b44-4347-bddb-7a0dd0f7b479",
                    "_gid": "GA1.2.1085584436.1595559677",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "s_v_web_id": "verify_kczo59ky_FlxKIV7C_zhEr_4z2C_8BnV_9GRIK1h2TVip",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "0eef99c5-4fe4-4cfe-abe2-5b34a3bcbb02",
                    "data-unique-id": "2e27d230-ce3d-11ea-ad68-83a977aed8cc",
                    "SESSION": "b0f4bb9a-3ad2-40be-ad79-e473540252f2",
                    "_gat": "1",
                    "reg_prepareId": "1738498487c-1738498473b-4e13-a558-df609f247eae",
                    "reg_focusId": "1812fb5d-034f-4e13-a558-17384984e5a",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTU5ODI0OTQ0NCwiaWF0IjoxNTk1NjU3NDQ0fQ.ZoOUyXDJZCeDyTifv2Lb3R0tGkkLOE6-Hj2XFUCLtAl_qk2hc9-ly-Gyvh2PVw0lfxR2Jxj9DMaeRgOnO9akSw",
                    "user_persistence": "0a3a3a87-2844-47be-90a5-9cc3e1120cec",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595657444",
                    "SLARDAR_WEB_ID": "ab29576c-6721-4297-b655-037dcf40f27c",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/document/get")
            .post("https://api2.${host}/v3/api/document/get")
            .with_headers(
                **{
                    "content-length": "23",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTU5ODI0OTQ0NCwiaWF0IjoxNTk1NjU3NDQ0fQ.ZoOUyXDJZCeDyTifv2Lb3R0tGkkLOE6-Hj2XFUCLtAl_qk2hc9-ly-Gyvh2PVw0lfxR2Jxj9DMaeRgOnO9akSw",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "2e27d230-ce3d-11ea-ad68-83a977aed8cc",
                    "x-request-id": "3c171294-29bb-4bcc-b834-98b2f7551707",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/doc$docId",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
                }
            )
            .with_json({"docId": "$docId"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/v3/api/user/current_level")
            .post("https://api2.${host}/v3/api/user/current_level")
            .with_headers(
                **{
                    "content-length": "29",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTU5ODI0OTQ0NCwiaWF0IjoxNTk1NjU3NDQ0fQ.ZoOUyXDJZCeDyTifv2Lb3R0tGkkLOE6-Hj2XFUCLtAl_qk2hc9-ly-Gyvh2PVw0lfxR2Jxj9DMaeRgOnO9akSw",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "2e27d230-ce3d-11ea-ad68-83a977aed8cc",
                    "x-request-id": "317c2ca0-e0ef-4914-9aef-ad1a34a8d073",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/doc$docId",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
                }
            )
            .with_json({"document_id": "$docId"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "OK")
        ),
        Step(
            RunRequest("/v3/api/user/current_user")
            .post("https://api2.${host}/v3/api/user/current_user")
            .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTU5ODI0OTQ0NCwiaWF0IjoxNTk1NjU3NDQ0fQ.ZoOUyXDJZCeDyTifv2Lb3R0tGkkLOE6-Hj2XFUCLtAl_qk2hc9-ly-Gyvh2PVw0lfxR2Jxj9DMaeRgOnO9akSw",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "2e27d230-ce3d-11ea-ad68-83a977aed8cc",
                    "x-request-id": "030e14d8-25a7-4714-b471-74baf29073d4",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/doc$docId",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
                }
            )
            .with_data("")
            .extract()
            .with_jmespath("body.data.id", "userId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
        ),
        Step(
            RunRequest("/v3/api/user/get_invite_count")
            .get("https://api2.${host}/v3/api/user/get_invite_count")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTU5ODI0OTQ0NCwiaWF0IjoxNTk1NjU3NDQ0fQ.ZoOUyXDJZCeDyTifv2Lb3R0tGkkLOE6-Hj2XFUCLtAl_qk2hc9-ly-Gyvh2PVw0lfxR2Jxj9DMaeRgOnO9akSw",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "2e27d230-ce3d-11ea-ad68-83a977aed8cc",
                    "x-request-id": "c7d2b0da-3a9f-4313-ab07-d48a584ab78c",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/doc$docId",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .get("https://api2.${host}/v3/api/colla/register")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTU5ODI0OTQ0NCwiaWF0IjoxNTk1NjU3NDQ0fQ.ZoOUyXDJZCeDyTifv2Lb3R0tGkkLOE6-Hj2XFUCLtAl_qk2hc9-ly-Gyvh2PVw0lfxR2Jxj9DMaeRgOnO9akSw",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "2e27d230-ce3d-11ea-ad68-83a977aed8cc",
                    "x-request-id": "d0f3aa47-15ab-4d8c-85bf-c651e99a85a5",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/doc$docId",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
            .post("https://api2.${host}/v3/api/user/get_user_params")
            .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTU5ODI0OTQ0NCwiaWF0IjoxNTk1NjU3NDQ0fQ.ZoOUyXDJZCeDyTifv2Lb3R0tGkkLOE6-Hj2XFUCLtAl_qk2hc9-ly-Gyvh2PVw0lfxR2Jxj9DMaeRgOnO9akSw",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "2e27d230-ce3d-11ea-ad68-83a977aed8cc",
                    "x-request-id": "cab6e13f-e8a0-4439-bdcc-c0047aa56aad",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/doc$docId",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .options("https://api2.${host}/v3/api/colla/members")
            .with_params(**{"memberId": "$memberId", "documentId": "$docId"})
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "GET",
                    "access-control-request-headers": "data-unique-id,jwt-token,request-id,x-request-id",
                    "origin": "https://${host}",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/doc$docId",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .get("https://api2.${host}/v3/api/colla/members")
            .with_params(**{"memberId": "$memberId", "documentId": "$docId"})
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTU5ODI0OTQ0NCwiaWF0IjoxNTk1NjU3NDQ0fQ.ZoOUyXDJZCeDyTifv2Lb3R0tGkkLOE6-Hj2XFUCLtAl_qk2hc9-ly-Gyvh2PVw0lfxR2Jxj9DMaeRgOnO9akSw",
                    "request-id": "members:$memberId:1595657453705",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "2e27d230-ce3d-11ea-ad68-83a977aed8cc",
                    "x-request-id": "366c7201-0990-4719-bc5a-79b35855aa34",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/doc${docId}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.${host}/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "513",
                    "member-id": "$memberId",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "2e27d230-ce3d-11ea-ad68-83a977aed8cc",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTU5ODI0OTQ0NCwiaWF0IjoxNTk1NjU3NDQ0fQ.ZoOUyXDJZCeDyTifv2Lb3R0tGkkLOE6-Hj2XFUCLtAl_qk2hc9-ly-Gyvh2PVw0lfxR2Jxj9DMaeRgOnO9akSw",
                    "request-id": "MESSAGE:$userId:$memberId:3",
                    "x-request-id": "46c492c2-406e-46f4-9172-6fa1e7ab11c2",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/doc$docId",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 3,
                    "requestId": "MESSAGE:$userId:$memberId:3",
                    "token": "$docId",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docId",
                            "version": 0,
                            "content": [
                                {
                                    "name": "nameChanged",
                                    "title": "$title",
                                    "original": "",
                                },
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.6",
                        "appVersion": "1.0.0.268",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .with_variables(nodeId="${gen_nodeId()}")
            .post("https://api2.${host}/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "720",
                    "member-id": "$memberId",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "2e27d230-ce3d-11ea-ad68-83a977aed8cc",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTU5ODI0OTQ0NCwiaWF0IjoxNTk1NjU3NDQ0fQ.ZoOUyXDJZCeDyTifv2Lb3R0tGkkLOE6-Hj2XFUCLtAl_qk2hc9-ly-Gyvh2PVw0lfxR2Jxj9DMaeRgOnO9akSw",
                    "request-id": "MESSAGE:$userId:$memberId:5",
                    "x-request-id": "fe707a91-9450-4218-9812-f7f620253b45",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/doc$docId",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 5,
                    "requestId": "MESSAGE:$userId:$memberId:5",
                    "token": "$docId",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docId",
                            "version": 1,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 0,
                                            "parentId": None,
                                            "node": {
                                                "id": "$nodeId",
                                                "text": "",
                                                "modified": "${get_timestamp()}",
                                                "children": [],
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                },
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "$nodeId",
                                                "text": "<span>$node1Text</span>",
                                                "modified": "${get_timestamp()}",
                                            },
                                            "original": {
                                                "id": "$nodeId",
                                                "text": "",
                                                "modified": "${get_timestamp()}",
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                },
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.6",
                        "appVersion": "1.0.0.268",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .with_variables(nodeId="${gen_nodeId()}")
            .post("https://api2.${host}/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "720",
                    "member-id": "$memberId",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "2e27d230-ce3d-11ea-ad68-83a977aed8cc",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTU5ODI0OTQ0NCwiaWF0IjoxNTk1NjU3NDQ0fQ.ZoOUyXDJZCeDyTifv2Lb3R0tGkkLOE6-Hj2XFUCLtAl_qk2hc9-ly-Gyvh2PVw0lfxR2Jxj9DMaeRgOnO9akSw",
                    "request-id": "MESSAGE:$userId:$memberId:7",
                    "x-request-id": "84e03397-b068-4fb4-80db-479207257de2",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/doc$docId",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 7,
                    "requestId": "MESSAGE:$userId:$memberId:7",
                    "token": "$docId",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docId",
                            "version": 2,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 1,
                                            "parentId": None,
                                            "node": {
                                                "id": "$nodeId",
                                                "text": "",
                                                "modified": "${get_timestamp()}",
                                                "children": [],
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                },
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "$nodeId",
                                                "text": "<span>$node2Text</span>",
                                                "modified": "${get_timestamp()}",
                                            },
                                            "original": {
                                                "id": "$nodeId",
                                                "text": "",
                                                "modified": "${get_timestamp()}",
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                },
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.6",
                        "appVersion": "1.0.0.268",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
        ),
    ]


if __name__ == "__main__":
    TestCaseMubuCreateDoc().test_start()
