# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/mubu_login.har


from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseMubuLogin(HttpRunner):

    config = (
        Config("login mubu")
        .variables(**{"host": "mubu.com"})
        .variables(phone="18613143458", password="moFrwx$!kz3RTRm@Q*aV")
        .verify(False)
        .base_url("https://${host}/")
    )

    teststeps = [
        Step(
            RunRequest("/")
            .get("/")
            .with_headers(
                **{
                    "cache-control": "max-age=0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1523574909.1567243126",
                    "mubu_inner": "1",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1594282707",
                    "data_unique_id": "c1e5cc1b-2b44-4347-bddb-7a0dd0f7b479",
                    "_gid": "GA1.2.1085584436.1595559677",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "s_v_web_id": "verify_kczo59ky_FlxKIV7C_zhEr_4z2C_8BnV_9GRIK1h2TVip",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "0eef99c5-4fe4-4cfe-abe2-5b34a3bcbb02",
                    "data-unique-id": "2e27d230-ce3d-11ea-ad68-83a977aed8cc",
                    "reg_prepareId": "1738496e4e5-1738496e30c-454a-b627-0f23a2922bdf",
                    "reg_focusId": "965a3204-4671-454a-b627-1738496e6fb",
                    "SESSION": "b0f4bb9a-3ad2-40be-ad79-e473540252f2",
                    "_gat": "1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595657415",
                    "SLARDAR_WEB_ID": "15341965-7485-41c7-bbab-ca5d9e3df1a7",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login")
            .get("/login")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1523574909.1567243126",
                    "mubu_inner": "1",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1594282707",
                    "data_unique_id": "c1e5cc1b-2b44-4347-bddb-7a0dd0f7b479",
                    "_gid": "GA1.2.1085584436.1595559677",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "s_v_web_id": "verify_kczo59ky_FlxKIV7C_zhEr_4z2C_8BnV_9GRIK1h2TVip",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "0eef99c5-4fe4-4cfe-abe2-5b34a3bcbb02",
                    "data-unique-id": "2e27d230-ce3d-11ea-ad68-83a977aed8cc",
                    "reg_prepareId": "1738496e4e5-1738496e30c-454a-b627-0f23a2922bdf",
                    "reg_focusId": "965a3204-4671-454a-b627-1738496e6fb",
                    "SESSION": "b0f4bb9a-3ad2-40be-ad79-e473540252f2",
                    "_gat": "1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595657431",
                    "SLARDAR_WEB_ID": "db1dc4b6-530e-4c6d-9ca2-9e003322f468",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login/password")
            .get("/login/password")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/login",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1523574909.1567243126",
                    "mubu_inner": "1",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1594282707",
                    "data_unique_id": "c1e5cc1b-2b44-4347-bddb-7a0dd0f7b479",
                    "_gid": "GA1.2.1085584436.1595559677",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "s_v_web_id": "verify_kczo59ky_FlxKIV7C_zhEr_4z2C_8BnV_9GRIK1h2TVip",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "0eef99c5-4fe4-4cfe-abe2-5b34a3bcbb02",
                    "data-unique-id": "2e27d230-ce3d-11ea-ad68-83a977aed8cc",
                    "SESSION": "b0f4bb9a-3ad2-40be-ad79-e473540252f2",
                    "_gat": "1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595657439",
                    "SLARDAR_WEB_ID": "d9963dbc-d584-419e-ab27-cab3679f0a10",
                    "reg_prepareId": "1738498487c-1738498473b-4e13-a558-df609f247eae",
                    "reg_focusId": "1812fb5d-034f-4e13-a558-17384984e5a",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/login/submit")
            .post("/api/login/submit")
            .with_headers(
                **{
                    "content-length": "65",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1523574909.1567243126",
                    "mubu_inner": "1",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1594282707",
                    "data_unique_id": "c1e5cc1b-2b44-4347-bddb-7a0dd0f7b479",
                    "_gid": "GA1.2.1085584436.1595559677",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "s_v_web_id": "verify_kczo59ky_FlxKIV7C_zhEr_4z2C_8BnV_9GRIK1h2TVip",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "0eef99c5-4fe4-4cfe-abe2-5b34a3bcbb02",
                    "data-unique-id": "2e27d230-ce3d-11ea-ad68-83a977aed8cc",
                    "SESSION": "b0f4bb9a-3ad2-40be-ad79-e473540252f2",
                    "_gat": "1",
                    "reg_prepareId": "1738498487c-1738498473b-4e13-a558-df609f247eae",
                    "reg_focusId": "1812fb5d-034f-4e13-a558-17384984e5a",
                    "SLARDAR_WEB_ID": "34c9f719-b0b4-43f2-b991-8d2f95868779",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595657441",
                }
            )
            .with_data(
                {"phone": "$phone", "password": "$password", "remember": "true",}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
            .assert_equal("body.data.next", "/list")
        ),
        Step(
            RunRequest("/list")
            .get("/list")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1523574909.1567243126",
                    "mubu_inner": "1",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1594282707",
                    "data_unique_id": "c1e5cc1b-2b44-4347-bddb-7a0dd0f7b479",
                    "_gid": "GA1.2.1085584436.1595559677",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "s_v_web_id": "verify_kczo59ky_FlxKIV7C_zhEr_4z2C_8BnV_9GRIK1h2TVip",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "0eef99c5-4fe4-4cfe-abe2-5b34a3bcbb02",
                    "data-unique-id": "2e27d230-ce3d-11ea-ad68-83a977aed8cc",
                    "SESSION": "b0f4bb9a-3ad2-40be-ad79-e473540252f2",
                    "_gat": "1",
                    "reg_prepareId": "1738498487c-1738498473b-4e13-a558-df609f247eae",
                    "reg_focusId": "1812fb5d-034f-4e13-a558-17384984e5a",
                    "SLARDAR_WEB_ID": "34c9f719-b0b4-43f2-b991-8d2f95868779",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595657441",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTU5ODI0OTQ0NCwiaWF0IjoxNTk1NjU3NDQ0fQ.ZoOUyXDJZCeDyTifv2Lb3R0tGkkLOE6-Hj2XFUCLtAl_qk2hc9-ly-Gyvh2PVw0lfxR2Jxj9DMaeRgOnO9akSw",
                    "user_persistence": "0a3a3a87-2844-47be-90a5-9cc3e1120cec",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/list/tip_new_update")
            .post("/api/list/tip_new_update")
            .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-requested-with": "XMLHttpRequest",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1523574909.1567243126",
                    "mubu_inner": "1",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1594282707",
                    "data_unique_id": "c1e5cc1b-2b44-4347-bddb-7a0dd0f7b479",
                    "_gid": "GA1.2.1085584436.1595559677",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "s_v_web_id": "verify_kczo59ky_FlxKIV7C_zhEr_4z2C_8BnV_9GRIK1h2TVip",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "0eef99c5-4fe4-4cfe-abe2-5b34a3bcbb02",
                    "data-unique-id": "2e27d230-ce3d-11ea-ad68-83a977aed8cc",
                    "SESSION": "b0f4bb9a-3ad2-40be-ad79-e473540252f2",
                    "_gat": "1",
                    "reg_prepareId": "1738498487c-1738498473b-4e13-a558-df609f247eae",
                    "reg_focusId": "1812fb5d-034f-4e13-a558-17384984e5a",
                    "SLARDAR_WEB_ID": "34c9f719-b0b4-43f2-b991-8d2f95868779",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595657441",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTU5ODI0OTQ0NCwiaWF0IjoxNTk1NjU3NDQ0fQ.ZoOUyXDJZCeDyTifv2Lb3R0tGkkLOE6-Hj2XFUCLtAl_qk2hc9-ly-Gyvh2PVw0lfxR2Jxj9DMaeRgOnO9akSw",
                    "user_persistence": "0a3a3a87-2844-47be-90a5-9cc3e1120cec",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
            .assert_equal("body.data.tip", True)
        ),
        Step(
            RunRequest("/api/list/get")
            .post("/api/list/get")
            .with_headers(
                **{
                    "content-length": "38",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1523574909.1567243126",
                    "mubu_inner": "1",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1594282707",
                    "data_unique_id": "c1e5cc1b-2b44-4347-bddb-7a0dd0f7b479",
                    "_gid": "GA1.2.1085584436.1595559677",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "s_v_web_id": "verify_kczo59ky_FlxKIV7C_zhEr_4z2C_8BnV_9GRIK1h2TVip",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "0eef99c5-4fe4-4cfe-abe2-5b34a3bcbb02",
                    "data-unique-id": "2e27d230-ce3d-11ea-ad68-83a977aed8cc",
                    "SESSION": "b0f4bb9a-3ad2-40be-ad79-e473540252f2",
                    "_gat": "1",
                    "reg_prepareId": "1738498487c-1738498473b-4e13-a558-df609f247eae",
                    "reg_focusId": "1812fb5d-034f-4e13-a558-17384984e5a",
                    "SLARDAR_WEB_ID": "34c9f719-b0b4-43f2-b991-8d2f95868779",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595657441",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTU5ODI0OTQ0NCwiaWF0IjoxNTk1NjU3NDQ0fQ.ZoOUyXDJZCeDyTifv2Lb3R0tGkkLOE6-Hj2XFUCLtAl_qk2hc9-ly-Gyvh2PVw0lfxR2Jxj9DMaeRgOnO9akSw",
                    "user_persistence": "0a3a3a87-2844-47be-90a5-9cc3e1120cec",
                }
            )
            .with_data({"folderId": "0", "sort": "name", "keywords": "", "source": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
            .assert_equal("body.data.folderId", "0")
            .assert_length_greater_than("body.data.folders", "${sum_two(2, 3)}")
            .assert_equal("body.data.folders[0].name", "分享 & 培训")
        ),
        Step(
            RunRequest("/api/message/get_message_unread")
            .post("/api/message/get_message_unread")
            .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-requested-with": "XMLHttpRequest",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1523574909.1567243126",
                    "mubu_inner": "1",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1594282707",
                    "data_unique_id": "c1e5cc1b-2b44-4347-bddb-7a0dd0f7b479",
                    "_gid": "GA1.2.1085584436.1595559677",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "s_v_web_id": "verify_kczo59ky_FlxKIV7C_zhEr_4z2C_8BnV_9GRIK1h2TVip",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "0eef99c5-4fe4-4cfe-abe2-5b34a3bcbb02",
                    "data-unique-id": "2e27d230-ce3d-11ea-ad68-83a977aed8cc",
                    "SESSION": "b0f4bb9a-3ad2-40be-ad79-e473540252f2",
                    "_gat": "1",
                    "reg_prepareId": "1738498487c-1738498473b-4e13-a558-df609f247eae",
                    "reg_focusId": "1812fb5d-034f-4e13-a558-17384984e5a",
                    "SLARDAR_WEB_ID": "34c9f719-b0b4-43f2-b991-8d2f95868779",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595657441",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTU5ODI0OTQ0NCwiaWF0IjoxNTk1NjU3NDQ0fQ.ZoOUyXDJZCeDyTifv2Lb3R0tGkkLOE6-Hj2XFUCLtAl_qk2hc9-ly-Gyvh2PVw0lfxR2Jxj9DMaeRgOnO9akSw",
                    "user_persistence": "0a3a3a87-2844-47be-90a5-9cc3e1120cec",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubuLogin().test_start()
